package se.rivta.itintegration.test.TestProcessTakNotification.v1.rivtabp21;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.9
 * Mon Dec 02 12:36:24 CET 2013
 * Generated source version: 2.1.9
 * 
 */
 
@WebService(targetNamespace = "urn:riv:itintegration:test:TestProcessTakNotification:1:rivtabp21", name = "TestProcessTakNotificationResponderInterface")
@XmlSeeAlso({se.rivta.itintegration.notification.v1.ObjectFactory.class,se.rivta.itintegration.test.TestProcessTakNotificationResponder.v1.rivtabp21.ObjectFactory.class,se.rivta.itintegration.test.v1.ObjectFactory.class,se.rivta.itintegration.registry.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestProcessTakNotificationResponderInterface {

    @WebResult(name = "TestProcessTakNotificationResponse", targetNamespace = "urn:riv:itintegration:test:TestProcessTakNotificationResponder:1", partName = "parameters")
    @WebMethod(operationName = "TestProcessTakNotification", action = "urn:riv:itintegration:test:TestProcessTakNotificationResponder:1:TestProcessTakNotification")
    public se.rivta.itintegration.test.TestProcessTakNotificationResponder.v1.rivtabp21.TestProcessTakNotificationResponseType testProcessTakNotification(
            @WebParam(partName = "LogicalAddress", name = "LogicalAddress", targetNamespace = "urn:riv:itintegration:registry:1", header = true)
            String logicalAddress,
            @WebParam(partName = "parameters", name = "TestProcessTakNotification", targetNamespace = "urn:riv:itintegration:test:TestProcessTakNotificationResponder:1")
            se.rivta.itintegration.test.TestProcessTakNotificationResponder.v1.rivtabp21.TestProcessTakNotificationType parameters
    );
}
